#!/usr/bin/env bash
# bails on error
set -e

# print command being run
set -x

# Ensure relevant yii commands are present
docker-compose run --rm console ./yii | grep fetch-reports

# Run accepance tests
docker-compose run --rm console ./vendor/codeception/codeception/codecept -c console/codeception.yml run acceptance