- name: Restore database on RDS instance
  hosts: localhost
  connection: local

  tasks:

    - name: "Test pg_restore"
      shell: "export PGPASSWORD='{{ gigadb_db_password }}'; /opt/local/bin/pg_restore -h rds-server-staging.cfkc0cbc20ii.ap-east-1.rds.amazonaws.com -p 5432 -d gigadb -U gigadb /Volumes/PLEXTOR/PhpstormProjects/gigadb-website/sql/production_like.pgdmp"
      register: "output"

    - debug: var=output.stdout_lines

#  roles:
#    - role: ../../roles/rds-restore-database
