- name: Install pre-requisites to Docker-CE
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: enable Docker-CE stable repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Disable Centos firewall for now (still have AWS SG safety net)
  systemd:
    name: firewalld
    enabled: no

- name: Install Docker-CE package and associated packages
  yum:
    name: docker-ce, docker-ce-cli, containerd.io
    state: present

